# Generated by Django 5.1.2 on 2024-11-20 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0002_caixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixapdv',
            name='caixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caixa.caixa'),
        ),
    ]
