# Generated by Django 5.1.2 on 2025-04-14 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0004_operacaocaixa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caixapdv',
            name='payment_method',
        ),
        migrations.CreateModel(
            name='PagamentoCaixaPdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('pix', 'Pix')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caixa_pdv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='caixa.caixapdv')),
            ],
        ),
    ]
