# Generated by Django 5.1.2 on 2025-04-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0005_remove_caixapdv_payment_method_pagamentocaixapdv'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixapdv',
            name='payment_method',
            field=models.CharField(default='N/D', max_length=50),
        ),
        migrations.DeleteModel(
            name='PagamentoCaixaPdv',
        ),
    ]
