# Generated by Django 5.1.2 on 2024-11-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='limite_credito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Limite de Crédito'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='limite_credito_ativo',
            field=models.BooleanField(default=False, verbose_name='Ativar Limite de Crédito'),
        ),
    ]
