# Generated by Django 5.1.2 on 2024-11-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_cliente_limite_credito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
