# Generated by Django 5.1.2 on 2024-11-07 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comanda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comanda',
            options={'get_latest_by': 'created_at'},
        ),
    ]
