# Generated by Django 5.1.2 on 2024-11-08 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_cpf'),
        ('comanda', '0002_alter_comanda_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comandafinalizada',
            name='comanda',
        ),
        migrations.AddField(
            model_name='comandafinalizada',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
    ]
