# Generated by Django 5.1.2 on 2024-11-08 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_cpf'),
        ('comanda', '0003_remove_comandafinalizada_comanda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='comanda',
            name='produtos',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada')], default='aberta', max_length=10),
        ),
        migrations.DeleteModel(
            name='ComandaFinalizada',
        ),
    ]
