# Generated by Django 5.1.2 on 2024-11-10 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comanda', '0004_comanda_cliente_comanda_produtos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comanda',
            name='produtos',
        ),
    ]
