# Generated by Django 5.1.2 on 2024-11-17 03:35

import django.db.models.deletion
import provendas.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to=provendas.utils.caminho_upload)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True)),
                ('preco_de_venda', models.DecimalField(decimal_places=2, max_digits=8)),
                ('preco_de_custo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantidade_estoque', models.IntegerField(blank=True, null=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to=provendas.utils.caminho_upload)),
                ('status', models.CharField(choices=[('ativado', 'Ativado'), ('desativado', 'Desativado')], default='ativado', max_length=10)),
                ('controle_estoque', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='estoque.categoriaproduto')),
            ],
        ),
    ]
