# Generated by Django 5.1.2 on 2024-10-31 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='tipo_cadastro',
        ),
    ]
