# Generated by Django 5.1.2 on 2024-10-31 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_remove_produto_tipo_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tipo_cadastro',
            field=models.CharField(choices=[('simples', 'Produto Simples'), ('multiplo', 'Produto com Múltiplos Valores'), ('promocional', 'Produto Promocional'), ('validade', 'Produto com Data de Validade')], default='simples', max_length=20),
        ),
    ]
