# Generated by Django 5.1.2 on 2024-11-01 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_produto_tipo_cadastro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='variavel_nome',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='variavel_preco_custo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='variavel_preco_venda',
        ),
        migrations.CreateModel(
            name='ProdutoVariacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_variacao', models.CharField(max_length=255)),
                ('preco_custo_variacao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('preco_venda_variacao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='estoque.produto')),
            ],
        ),
    ]
