# Generated by Django 5.1.2 on 2024-11-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_remove_produto_variavel_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtovariacao',
            name='nome_variacao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produtovariacao',
            name='preco_custo_variacao',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produtovariacao',
            name='preco_venda_variacao',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
