# Generated by Django 5.1.2 on 2024-11-01 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_alter_produtovariacao_nome_variacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='data_expiracao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco_promocional',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='slug',
        ),
    ]
