# Generated by Django 5.1.2 on 2024-11-01 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_remove_produto_data_expiracao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='data_validade',
        ),
    ]
