# Generated by Django 5.1.2 on 2024-11-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_alter_produto_tipo_cadastro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='preco_custo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco_venda',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='quantidade_estoque',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='tipo_cadastro',
        ),
        migrations.AddField(
            model_name='produtovariacao',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
