# Generated by Django 5.1.2 on 2024-11-01 13:20

import provendas.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_remove_produto_preco_custo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=provendas.utils.caminho_upload),
        ),
    ]
