# Generated by Django 5.1.2 on 2024-11-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_alter_produto_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade_estoque',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProdutoVariacao',
        ),
    ]
