# Generated by Django 5.1.2 on 2024-11-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0011_produto_preco_produto_quantidade_estoque_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preco',
            new_name='preco_de_cursto',
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_de_venda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
