# Generated by Django 5.1.2 on 2024-11-01 20:40

import provendas.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0012_rename_preco_produto_preco_de_cursto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaproduto',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=provendas.utils.caminho_upload),
        ),
    ]
