# Generated by Django 5.1.2 on 2024-11-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0013_categoriaproduto_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='controle_estoque',
            field=models.BooleanField(default=True),
        ),
    ]
