# Generated by Django 5.1.2 on 2024-11-12 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_alter_cliente_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aplicacao', models.CharField(blank=True, max_length=255, null=True)),
                ('cor_principal', models.CharField(blank=True, max_length=7, null=True)),
                ('cliente_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
            ],
        ),
    ]
