# Generated by Django 5.1.2 on 2024-11-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='cor_secundaria',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
