# Generated by Django 5.1.2 on 2024-11-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0002_configuracao_cor_secundaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracao',
            name='cor_principal',
        ),
        migrations.AddField(
            model_name='configuracao',
            name='cor_primaria',
            field=models.CharField(default='#ff670f', max_length=7),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='logo_empresa',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='cor_secundaria',
            field=models.CharField(default='#ffd30f', max_length=7),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='nome_aplicacao',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
