# Generated by Django 5.1.2 on 2024-11-12 19:22

import provendas.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0003_remove_configuracao_cor_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='icone_aplicacao',
            field=models.ImageField(blank=True, null=True, upload_to=provendas.utils.caminho_upload),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='cliente_padrao',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='cor_primaria',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='cor_secundaria',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='logo_empresa',
            field=models.ImageField(blank=True, null=True, upload_to=provendas.utils.caminho_upload),
        ),
    ]
