# Generated by Django 5.1.2 on 2024-11-12 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_cpf'),
        ('configuracoes', '0004_configuracao_icone_aplicacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='cliente_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente'),
        ),
    ]
