# Generated by Django 5.1.2 on 2024-11-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0005_alter_configuracao_cliente_padrao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='cor_primaria',
            field=models.CharField(default='#ff970f', max_length=7),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='cor_secundaria',
            field=models.CharField(default='#ffcb0f', max_length=7),
        ),
    ]
