# Generated by Django 5.1.2 on 2024-11-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0006_alter_configuracao_cor_primaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='gerar_codigo_barra_automatico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='gerenciar_abertura_fechamento_caixa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='cor_primaria',
            field=models.CharField(default='#16bb6e', max_length=7),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='cor_secundaria',
            field=models.CharField(default='#09ec41', max_length=7),
        ),
    ]
