# Generated by Django 5.1.2 on 2024-11-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0007_configuracao_gerar_codigo_barra_automatico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='modoLeitorCodigoDeBarra',
            field=models.BooleanField(default=False),
        ),
    ]
