# Generated by Django 5.1.2 on 2024-11-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencas', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensekey',
            name='status',
            field=models.CharField(choices=[('Ativada', 'Ativada'), ('Pendente', 'Pendente'), ('Cancelada', 'Cancelada')], default='Pendente', max_length=10),
        ),
    ]
