# Generated by Django 5.1.2 on 2024-11-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencas', '0004_remove_licensekey_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensekey',
            name='status',
            field=models.CharField(choices=[('ATIVADO', 'Ativado'), ('VENCIDA', 'Vencida')], default='VENCIDA', max_length=10),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
