# Generated by Django 5.1.2 on 2024-11-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencas', '0005_licensekey_status_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensekey',
            name='system_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
