# Generated by Django 5.1.2 on 2024-11-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licencas', '0007_licensekey_unique_key_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licensekey',
            name='system_identifier',
        ),
    ]
