# Generated by Django 5.1.2 on 2024-11-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencas', '0009_remove_licensekey_unique_key_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='licensekey',
            name='status',
            field=models.CharField(choices=[('ATIVADO', 'Ativado'), ('VENCIDA', 'Vencida')], default='VENCIDA', max_length=20),
        ),
    ]
