# Generated by Django 5.1.2 on 2024-11-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencas', '0010_alter_licensekey_key_alter_licensekey_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensekey',
            name='type',
            field=models.CharField(choices=[('TRIAL', 'Trial'), ('PAID', 'Paga'), ('PREMIUM', 'Premium')], default='TRIAL', max_length=20),
        ),
    ]
