# Generated by Django 5.1.2 on 2024-11-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencas', '0011_licensekey_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseKeyValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='licensekey',
            name='type',
        ),
    ]
